export const ROUTES = {
  HOME: '/',
  FEATURES: '/features',
  HOW_IT_WORKS: '/how-it-works',
  AI: '/ai',
  ABOUT: '/about',
  FAQ: '/faq',
  CONTACT: '/contact',
  PRIVACY: '/privacy',
  TERMS: '/terms',

  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  VERIFY_EMAIL: '/verify-email',

  APP: '/app',
  DASHBOARD: '/app/dashboard',
  DISCOVER: '/app/discover',
  RECOMMENDATIONS: '/app/recommendations',
  CONNECTIONS: '/app/connections',
  MENTORS: '/app/mentors',
  LEARNERS: '/app/learners',
  PEERS: '/app/peers',
  SESSIONS: '/app/sessions',
  CALENDAR: '/app/calendar',
  CHAT: '/app/chat',
  NOTIFICATIONS: '/app/notifications',
  LEADERBOARD: '/app/leaderboard',
  ROADMAP: '/app/roadmap',
  PROFILE: '/app/profile',
  SETTINGS: '/app/settings',
  CERTIFICATES: '/app/certificates',
  ADMIN_DASHBOARD: '/admin',
  ADMIN_USERS: '/admin/users',
  ADMIN_INSTITUTIONS: '/admin/institutions',
  ADMIN_SKILLS: '/admin/skills',
  ADMIN_SESSIONS: '/admin/sessions',
  ADMIN_BADGES: '/admin/badges',
  ADMIN_CERTIFICATES: '/admin/certificates',
  ADMIN_REPORTS: '/admin/reports',
  ADMIN_AI: '/admin/ai',
  ADMIN_HEALTH: '/admin/health',
  ADMIN_ANALYTICS: '/admin/analytics',
  ADMIN_AUDIT_LOGS: '/admin/audit-logs',
  ADMIN_SETTINGS: '/admin/settings',
};

export const profileRoute = (id) => id ? `/app/profile/${id}` : '/app/profile';
export const chatRoute = (userId) => userId ? `/app/chat?user=${userId}` : '/app/chat';
